### ISSUE TITLE
Buy now and add to cart button should be fixed in bottom for mobile devices 

### ISSUE THREAD

**Issue by ab7022** [aashish-dhiman/E-Commerce#5]
Can i work on it?

**Comment by aashish-dhiman** [comment]
Yeah sure. Just make sure to use Tailwind CSS for styling.
Assigned to you.

**Comment by ab7022** [comment]
Maybe you should open a new issue for image container overflowing and merge this

**Comment by aashish-dhiman** [comment]
Let me take a look at this in a bit.
If you want to work on that, please open a issue and start working on it.
It'll be great.

**Comment by ab7022** [comment]
nope
